name: CI/CD for LibraryManagementSystem

on:
  push:
    branches:
      - main   # Run when you push to main

jobs:
  build-and-deploy:
    runs-on: self-hosted   # use your local self-hosted runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'   # adjust to your .NET version

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --configuration Release

    - name: Publish project
      run: dotnet publish -c Release -o ./publish

    - name: Deploy to IIS folder
      shell: powershell
      run: |
        Write-Output "Deploying to IIS..."
        Remove-Item -Recurse -Force "C:\inetpub\wwwroot\LibraryManagementSystem\*" -ErrorAction SilentlyContinue
        Copy-Item -Path publish\* -Destination "C:\inetpub\wwwroot\LibraryManagementSystem" -Recurse
        iisreset
